create table matches (
   id           varchar(36) not null,
   team_a       varchar(255) not null,
   team_b       varchar(255) not null,
   status       varchar(32) not null,
   score        text,
   series       varchar(255),
   match_date   date,
   last_updated timestamp not null,
   constraint pk_matches primary key ( id )
);

create index idx_matches_status on
   matches (
      status
   );

create index idx_matches_match_date on
   matches (
      match_date
   );

create index idx_matches_series on
   matches (
      series
   );


create table standings (
   id                bigint generated by default as identity,
   tournament_series varchar(255) not null,
   team_name         varchar(255) not null,
   played            integer not null,
   won               integer not null,
   lost              integer not null,
   points            integer not null,
   net_run_rate      double precision not null,
   constraint pk_standings primary key ( id ),
   constraint uk_standings_series_team unique ( tournament_series,
                                                team_name )
);

create index idx_standings_series on
   standings (
      tournament_series
   );

create index idx_standings_series_points on
   standings (
      tournament_series,
      points
   desc,
      net_run_rate
   desc );